apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-lab
  labels:
    app.kubernetes.io/name: kubevirt-lab
    app.kubernetes.io/part-of: kubevirt-exploration
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros-demo-dv
  namespace: kubevirt-lab
spec:
  source:
    http:
      url: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros-vm
  namespace: kubevirt-lab
  labels:
    app: cirros-demo
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: cirros-vm
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 256Mi
        devices:
          disks:
            - name: cloudinitdisk
              disk:
                bus: virtio
              bootOrder: 2
            - name: containerdisk
              disk:
                bus: virtio
              bootOrder: 1
      volumes:
        - name: containerdisk
          dataVolume:
            name: cirros-demo-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              datasource_list: [ None ]
              ssh_pwauth: False
